title: "IANZ"
production: true
data_directory: "~/Network-Shares/J-Drive-WLG-Shared/Indicators_aotearoa/Covid-19/IANZ v2/portal data/"
indicator_definitions: "config/ianz/ianz_indicators.json"
data_definitions: "config/ianz/ianz_data_definitions.json"
default_parameters:
  data_type: "TimeSeries"
  plot_function: "get_time_series_plot"
  data_service: "load_from_store"
primary_color: "#A9A9A9"
about_modal_html: "www/about_ianz.html"
download_modal_html: "www/download_modal_ianz.html"
data_store_filename: "data_store.RDS"
